#	$OpenBSD: Makefile,v 1.2 2001/01/29 02:05:45 niklas Exp $
#	$NetBSD: Makefile,v 1.2 1995/04/20 22:40:13 cgd Exp $

PROG=	setjmptest
SRCS=	jmptest.c

CFLAGS+= -DTEST_SETJMP

.include <bsd.regress.mk>
