#	$OpenBSD: Makefile,v 1.1 2009/04/09 01:24:43 martynas Exp $

PROG = ieetst
SRCS = drand.c econst.c eexp.c elog.c epow.c etanh.c etodec.c ieee.c \
       ieetst.c mtherr.c

.include <bsd.regress.mk>
