#	$OpenBSD: Makefile,v 1.1 2003/07/15 10:09:37 otto Exp $

REGRESS_TARGETS=        t1 t2 t3 t4 t5 t6 t7

.include <bsd.regress.mk>

t1:	malloc_general
	malloc_general ""

t2:	malloc_general
	malloc_general C

t3:	malloc_general
	malloc_general J

t4:	malloc_general
	malloc_general F

t5:	malloc_general
	malloc_general G

t6:	malloc_general
	malloc_general S

t7:	malloc_general
	malloc_general FGJ
